<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <RootNamespace>ENet.Benchmarks</RootNamespace>
    <AssemblyName>enet-bench</AssemblyName>
    <Optimize>true</Optimize>
    <TieredPGO>true</TieredPGO>
    <ServerGarbageCollector>false</ServerGarbageCollector>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Managed\ENet-CSharp.csproj" />
  </ItemGroup>

</Project>
